@startmindmap
* EventLoopGroup
** EventLoop
*** Channel
*** Channel
*** Channel
** EventLoop
*** Channel
*** Channel
*** Channel
** EventLoop
*** Channel
*** Channel
*** Channel
@endmindmap